#! /bin/bash
source /home/pi/microSWIFT/updatedmicroWave/testmicroWave/config/Config.dat

###########################################################################################
# read and write gps data from gpsd, without disrupting serial port /dev/ttyS0 using gpspipe 
###########################################################################################

# give date and time a variable             
dname=$(date +"%d%b%Y")
tname=$(date +"%H:%M:%S")
# specify directory to save file under 
directory=($dataDir$floatID'_GPS_'$dname'_'$tname'UTC_burst_'$burstInt.dat)
echo $directory
#-----------------------------------------------------------------------------------------
# loop begins 
#-----------------------------------------------------------------------------------------
while :
do
    # -r causes raw NMEA sentences to be output
    # -n causes specified count of sentences to be output before gpsdpipe exits
    # -t add a timestamp to each sentence output 
    # -o causes the collected data to be written to the specified file
    # log 100 sentences of raw NMEA gps data to specified directory with file time stamp
    gpspipe -r -n 14400 -o $directory
break 
#-----------------------------------------------------------------------------------------
# loop ends 
#-----------------------------------------------------------------------------------------
done 

#$PGRMO,GPVTG,1
#$PGRMO,GPGGA,1
#$PGRMO,GPRMC,1
#$PGRMO,,2
#$PGRMO,,3