#!/bin/bash

#read config file 
source /home/pi/microSWIFT/utils/Config.dat > /dev/null

#host username to send data to 
USERNAME=$shipUser
#host IP address to send data to 
HOST=$shipIP
#data and log directories in this pi
DATAPATH=$dataDir
LOGPATH=$logDir
#use date to organize data and logs within floadID folder
DATE="$(date +"%d%b%Y")"
DATESTRING=${DATE}
YESTERDAY="$(date -d "1 days ago" +"%d%b%Y")"
YESTERDAYSTRING=${YESTERDAY}
YEAR="$(date +"%Y")"
YEARSTRING=${YEAR}
#create new directory with floatID in config file 
REMOTEPATH=$shipDir/microSWIFT$floatID/$DATESTRING
#host password to send data to
PASSWORD=$shipPass

#initialize send data flag 
sendData=0

#turn wifi on 
sudo rfkill unblock wifi

#will most likely happen at the same time 
while [ "$sendData" -eq 0 ]
do 
    #try to find server to connect to 
    ping -c 1 $HOST ; echo $?

    #0 means host reachable
    #2 means unreachable
    if [ "$?" = 0 ]
    then 
        echo "Host found" 
        sshpass -p $PASSWORD rsync -r --include="*$DATESTRING*" --include="*$YESTERDAYSTRING*" --include ="*/" --exclude="*$YEARSTRING*" $DATAPATH $USERNAME@$HOST:$REMOTEPATH
	sshpass -p $PASSWORD rsync -r --include="*$DATESTRING*" --include="*$YESTERDAYSTRING*" --include ="*/" --exclude="*$YEARSTRING*" $LOGPATH $USERNAME@$HOST:$REMOTEPATH
        sendData=1
    else 
        echo "Host not found" 
    fi
	
done