#!/bin/bash
# Run record IMU for microSWIFT 

#directories and files needed 
berryIMUDir=/home/pi/microSWIFT/updatedmicroWave/testmicroWave/berryIMU
config=/home/pi/microSWIFT/updatedmicroWave/testmicroWave/config/Config.dat
configDir=/home/pi/microSWIFT/updatedmicroWave/testmicroWave/config/
lib=/usr/local/lib/python2.7/dist-packages

#get PIDs  
imuPID=$(ps -ef | grep "berryIMU.py" | grep -v grep | awk '{ print $2 }')
echo "imuPID=" $imuPID

#add directories needed to run temp,pressure,humidity app to pythonpath
export PYTHONPATH=$PYTHONPATH/$berryIMUDir:/$configDir

#=================================================================================
#Run app
#=================================================================================
echo " --- RUN RECORD AND SEND GPS APP ---"
python2 berryIMU.py $config &